download_steps = [
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.025,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.05,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.075,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "downloading",
        "percent": 0.05555555555555555,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.1,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "downloading",
        "percent": 0.1111111111111111,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.125,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "downloading",
        "percent": 0.16666666666666666,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.15,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "downloading",
        "percent": 0.2222222222222222,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.175,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "downloading",
        "percent": 0.2777777777777778,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.2,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "downloading",
        "percent": 0.3333333333333333,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.225,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "downloading",
        "percent": 0.3888888888888889,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.25,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "downloading",
        "percent": 0.4444444444444444,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.275,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "downloading",
        "percent": 0.5,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "merging pdf bai-yao-pu chapter 1",
        "percent": 0.1111111111111111,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "merging pdf bai-yao-pu chapter 1",
        "percent": 0.2222222222222222,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.3,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "merging pdf bai-yao-pu chapter 1",
        "percent": 0.3333333333333333,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "merging pdf bai-yao-pu chapter 1",
        "percent": 0.4444444444444444,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "merging pdf bai-yao-pu chapter 1",
        "percent": 0.5555555555555556,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "merging pdf bai-yao-pu chapter 1",
        "percent": 0.6666666666666666,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "merging pdf bai-yao-pu chapter 1",
        "percent": 0.7777777777777778,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "merging pdf bai-yao-pu chapter 1",
        "percent": 0.8888888888888888,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "merging pdf bai-yao-pu chapter 1",
        "percent": 1,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "merging pdf bai-yao-pu chapter 1",
        "percent": 0.9,
    },
    {
        "id": "chapter 1 bai-yao-pu",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2020/12/bai-yao-pu.jpg",
        "name": "finished",
        "percent": 1,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.325,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.35,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.375,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.4,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.425,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.45,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.475,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "downloading",
        "percent": 0.5,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.05,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.1,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.15,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.2,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.25,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.3,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.35,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.4,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.45,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.5,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.55,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.6,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.65,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.7,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.75,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.8,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.85,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.9,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.95,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 1,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "merging pdf one-piece chapter 680",
        "percent": 0.9,
    },
    {
        "id": "chapter 680 one-piece",
        "cover": "https://scansmangas.xyz/wp-content/uploads/2019/10/one-piece.jpg",
        "name": "finished",
        "percent": 1,
    },
]
